# Generated by Django 5.2.2 on 2025-06-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
