# Generated by Django 5.2.2 on 2025-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_user_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
